###############################################################################
#
# Copyright 2023 NXP
#
# SPDX-License-Identifier: GPL-2.0
#
###############################################################################

APP_NAME=app_scst

all:
	$(CC) main.c -o $(APP_NAME)
clean:
	rm -rf $(APP_NAME)
